DROP TABLE "XXUP"."XXUP_RIM_ACCTG_INFO" ;
CREATE TABLE "XXUP"."XXUP_RIM_ACCTG_INFO" 
   (	"ITEM_KEY" VARCHAR2(100 BYTE), 
	"SP_CODE_DISP" VARCHAR2(150 BYTE), 
	"FUND_CONTROLLER_DISP" VARCHAR2(150 BYTE)
   );

CREATE SYNONYM XXUP_RIM_ACCTG_INFO FOR XXUP.XXUP_RIM_ACCTG_INFO;