
DROP TABLE xxup.XXUP_RIM_TEAM_MEMBERS;

CREATE TABLE xxup.XXUP_RIM_TEAM_MEMBERS
(   
    rim_member_id NUMBER(15)
   ,line_no NUMBER(2) 
   ,transaction_no NUMBER(15) NOT NULL
   ,item_key VARCHAR2(100)
   ,FULL_NAME VARCHAR2(140 BYTE)
   ,POSITION VARCHAR2(140 BYTE)
   ,ORGANIZATION VARCHAR2(140 BYTE)
   ,PROJECT_ROLE VARCHAR2(140 BYTE)
   ,END_DATE DATE
   ,ATTRIBUTE1        VARCHAR2(140)  
   ,ATTRIBUTE2        VARCHAR2(140)  
   ,ATTRIBUTE3        VARCHAR2(140)  
   ,ATTRIBUTE4        VARCHAR2(140)  
   ,ATTRIBUTE5        VARCHAR2(140)  
   ,LAST_UPDATE_DATE  DATE           
   ,LAST_UPDATED_BY   NUMBER(15)     
   ,LAST_UPDATE_LOGIN NUMBER(15)    
   ,CREATED_BY        NUMBER(15)
   ,CREATION_DATE     DATE
   ,CONSTRAINT rim_mem_pk PRIMARY KEY(rim_member_id)
   -- ,CONSTRAINT rim_mem_fk
   --    FOREIGN KEY(transaction_no, item_key)
   --    REFERENCES xxup.xxup_rim_header(transaction_no, item_key)
   --    ON DELETE CASCADE
);

CREATE SYNONYM XXUP_RIM_TEAM_MEMBERS FOR xxup.XXUP_RIM_TEAM_MEMBERS;