package xxup.oracle.apps.per.rim.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

import xxup.oracle.apps.per.rim.server.RIMHelper;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMProjectStatusVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public RIMProjectStatusVOImpl() {
    }

    public void limitProjectStatus(String pUrl){
        System.out.println("receivedURL: " + pUrl);

      String criteria = "";  
      setWhereClauseParams(null);

      if(RIMHelper.C_FOR_CLSOUT_AC.equals(pUrl) ||
          RIMHelper.C_DON_FIN_REP_AC.equals(pUrl) ||
          RIMHelper.C_CLS_REP_VAL_AC.equals(pUrl) ||
          RIMHelper.C_CLOSED_AC.equals(pUrl) ||
          RIMHelper.C_COMPLETED_AC.equals(pUrl)) {

        if(pUrl.equals(RIMHelper.C_FOR_CLSOUT_AC.equals(pUrl))){
            criteria = RIMHelper.C_FINAL_FIN_REP_PS;            
            
        } else if(pUrl.equals(RIMHelper.C_DON_FIN_REP_AC.equals(pUrl))){
            criteria = RIMHelper.C_CLSOUT_REP_VAL_PS;            
            
        } else if(pUrl.equals(RIMHelper.C_CLS_REP_VAL_AC.equals(pUrl))){
            criteria = RIMHelper.C_CLOSED_PS;            
            
        
        } else if(pUrl.equals(RIMHelper.C_CLOSED_AC.equals(pUrl))){
            criteria = RIMHelper.C_COMPLETED_PS;            
            
        }

        setWhereClause("project_status = :1");
        setWhereClauseParam(0, criteria);
        executeQuery();  

      
      } else { // Create/Update 
        setWhereClause("project_status NOT IN (:1, :2, :3, :4, :5)");
        setWhereClauseParam(0, RIMHelper.C_CLOSEOUT_PS);
        setWhereClauseParam(1, RIMHelper.C_FINAL_FIN_REP_PS);
        setWhereClauseParam(2, RIMHelper.C_CLSOUT_REP_VAL_PS);
        setWhereClauseParam(3, RIMHelper.C_CLOSED_PS);
        setWhereClauseParam(4, RIMHelper.C_COMPLETED_PS);
        executeQuery();  

      }


      

    
  }
}
