package xxup.oracle.apps.per.rim.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMHeaderSummVOImpl extends RIMVOParent {
    /**This is the default constructor (do not remove)
     */
    public RIMHeaderSummVOImpl() {
    }

    protected static final String ALL_LEVEL = "ALL";
  
  protected static final String USER_LEVEL = "USER";
  
  protected static final String UNIT_LEVEL = "UNIT";
  
  protected static final String CU_LEVEL = "CU";
  
  public void showSummaryVO() {
    setWhereClause(null);
    setWhereClause("created_by = fnd_global.user_id");
    setOrderByClause("project_name");
    executeQuery();
  }
  
  public void initExistingPS(String transactionNo) {
    initExist(transactionNo);
  }
  
  public void initNewRecord() {
    super.initNewRecord();
  }
  
  public void showSummaryVO(String accessLevel) {
    setWhereClause(null);
    if (accessLevel.equals("ALL")) {
      setWhereClause("1=1");
    } else if (accessLevel.equals("CU")) {
      setWhereClause("created_by IN (SELECT user_id FROM fnd_user WHERE user_name IN (SELECT * FROM TABLE(xxup_get_users_per_cu(fnd_global.user_id))))");
    // } else if (accessLevel.equals("UNIT")) {
    //   setWhereClause("created_by IN (SELECT user_id FROM fnd_user WHERE user_name IN (SELECT * FROM TABLE(xxup_ps_inst_wf_pkg.get_users_per_unit(fnd_global.user_id))))");
    } else if (accessLevel.equals("USER")) {
      setWhereClause("project_leader_id = fnd_global.employee_id");
    } else {
      setWhereClause("project_leader_id = fnd_global.employee_id");
    }

    setOrderByClause("transaction_no");
    executeQuery();
  }
  
  void execWhereClause() {
    setWhereClause(null);
    setWhereClause("created_by = fnd_global.user_id");
    executeQuery();
  }

}
