package xxup.oracle.apps.per.rim.server;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMOldEndDtExtEOVOImpl extends RIMVOParent {
    /**This is the default constructor (do not remove)
     */
    public RIMOldEndDtExtEOVOImpl() {
    }
    
    public void initExist(String pItemKey){
        super.initExist(pItemKey);
    }
    
}
