package xxup.oracle.apps.per.rim.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMProjImpactEOVOImpl extends RIMVOParent {
    /**This is the default constructor (do not remove)
     */
    public RIMProjImpactEOVOImpl() {
    }
    
    public void initNewRecord(){
        super.initNewRecord();
    }

    public void initExist(String itemKey) {
        super.initExist(itemKey);
    }
}
