package xxup.oracle.apps.per.rim.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMAttachmentEOVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public RIMAttachmentEOVOImpl() {
    }


  //All attachments from different submissions referencing to original transaction
  public void initAttachments(String transactionNo) {
  	  String origItemKey = "RIM-" + transactionNo;
      setWhereClause(null);
      setWhereClause("item_key = :1");
      setWhereClauseParam(0, origItemKey);
      executeQuery();
  }
}
