package xxup.oracle.apps.per.rim.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMActionHistoryVOImpl extends OAViewObjectImpl {
    /**This is the default constructor (do not remove)
     */
    public RIMActionHistoryVOImpl() {
    }

    public void initApprovers(String itemKey) {
        //setMaxFetchSize(0);
    
        setWhereClauseParams(null);
        setWhereClause("item_key = :1");
        setWhereClauseParam(0, itemKey);
        executeQuery();
    }
}
