package xxup.oracle.apps.per.rim.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;

import xxup.oracle.apps.per.rim.schema.server.RIMFiscalDetailsEOImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMFiscalDetailsEOVORowImpl extends OAViewRowImpl {
    public static final int RIMFISCID = 0;
    public static final int TRANSACTIONNO = 1;
    public static final int CONSTITUENTUNIT = 2;
    public static final int RESPONSIBILITYCENTER = 3;
    public static final int COLLABORATINGAGENCY = 4;
    public static final int FUNDINGAGENCY = 5;
    public static final int SPCODE = 6;
    public static final int FUNDCONTROLLERID = 7;
    public static final int FAREXCLUDED = 8;
    public static final int ITEMKEY = 9;
    public static final int ATTRIBUTE1 = 10;
    public static final int ATTRIBUTE2 = 11;
    public static final int ATTRIBUTE3 = 12;
    public static final int ATTRIBUTE4 = 13;
    public static final int ATTRIBUTE5 = 14;
    public static final int LASTUPDATEDATE = 15;
    public static final int LASTUPDATEDBY = 16;
    public static final int LASTUPDATELOGIN = 17;
    public static final int CREATEDBY = 18;
    public static final int CREATIONDATE = 19;
    public static final int FUNDCONTROLLERDISP = 20;
    public static final int SPCODEDISP = 21;
    public static final int RESPONSIBILITYCENTERDISP = 22;
    public static final int DISABLEACCOUNTINGMODE = 23;
    public static final int DISABLEFUNDINGAGENCY = 24;

    /**This is the default constructor (do not remove)
     */
    public RIMFiscalDetailsEOVORowImpl() {
    }

    /**Gets RIMFiscalDetailsEO entity object.
     */
    public RIMFiscalDetailsEOImpl getRIMFiscalDetailsEO() {
        return (RIMFiscalDetailsEOImpl)getEntity(0);
    }

    /**Gets the attribute value for RIM_FISC_ID using the alias name RimFiscId
     */
    public Number getRimFiscId() {
        return (Number) getAttributeInternal(RIMFISCID);
    }

    /**Sets <code>value</code> as attribute value for RIM_FISC_ID using the alias name RimFiscId
     */
    public void setRimFiscId(Number value) {
        setAttributeInternal(RIMFISCID, value);
    }

    /**Gets the attribute value for TRANSACTION_NO using the alias name TransactionNo
     */
    public Number getTransactionNo() {
        return (Number) getAttributeInternal(TRANSACTIONNO);
    }

    /**Sets <code>value</code> as attribute value for TRANSACTION_NO using the alias name TransactionNo
     */
    public void setTransactionNo(Number value) {
        setAttributeInternal(TRANSACTIONNO, value);
    }

    /**Gets the attribute value for CONSTITUENT_UNIT using the alias name ConstituentUnit
     */
    public String getConstituentUnit() {
        return (String) getAttributeInternal(CONSTITUENTUNIT);
    }

    /**Sets <code>value</code> as attribute value for CONSTITUENT_UNIT using the alias name ConstituentUnit
     */
    public void setConstituentUnit(String value) {
        setAttributeInternal(CONSTITUENTUNIT, value);
    }

    /**Gets the attribute value for RESPONSIBILITY_CENTER using the alias name ResponsibilityCenter
     */
    public String getResponsibilityCenter() {
        return (String) getAttributeInternal(RESPONSIBILITYCENTER);
    }

    /**Sets <code>value</code> as attribute value for RESPONSIBILITY_CENTER using the alias name ResponsibilityCenter
     */
    public void setResponsibilityCenter(String value) {
        setAttributeInternal(RESPONSIBILITYCENTER, value);
    }

    /**Gets the attribute value for COLLABORATING_AGENCY using the alias name CollaboratingAgency
     */
    public String getCollaboratingAgency() {
        return (String) getAttributeInternal(COLLABORATINGAGENCY);
    }

    /**Sets <code>value</code> as attribute value for COLLABORATING_AGENCY using the alias name CollaboratingAgency
     */
    public void setCollaboratingAgency(String value) {
        setAttributeInternal(COLLABORATINGAGENCY, value);
    }

    /**Gets the attribute value for FUNDING_AGENCY using the alias name FundingAgency
     */
    public String getFundingAgency() {
        return (String) getAttributeInternal(FUNDINGAGENCY);
    }

    /**Sets <code>value</code> as attribute value for FUNDING_AGENCY using the alias name FundingAgency
     */
    public void setFundingAgency(String value) {
        setAttributeInternal(FUNDINGAGENCY, value);
    }

    /**Gets the attribute value for SP_CODE using the alias name SpCode
     */
    public String getSpCode() {
        return (String) getAttributeInternal(SPCODE);
    }

    /**Sets <code>value</code> as attribute value for SP_CODE using the alias name SpCode
     */
    public void setSpCode(String value) {
        setAttributeInternal(SPCODE, value);
    }

    /**Gets the attribute value for FUND_CONTROLLER_ID using the alias name FundControllerId
     */
    public Number getFundControllerId() {
        return (Number) getAttributeInternal(FUNDCONTROLLERID);
    }

    /**Sets <code>value</code> as attribute value for FUND_CONTROLLER_ID using the alias name FundControllerId
     */
    public void setFundControllerId(Number value) {
        setAttributeInternal(FUNDCONTROLLERID, value);
    }

    /**Gets the attribute value for FAR_EXCLUDED using the alias name FarExcluded
     */
    public String getFarExcluded() {
        return (String) getAttributeInternal(FAREXCLUDED);
    }

    /**Sets <code>value</code> as attribute value for FAR_EXCLUDED using the alias name FarExcluded
     */
    public void setFarExcluded(String value) {
        setAttributeInternal(FAREXCLUDED, value);
    }

    /**Gets the attribute value for ITEM_KEY using the alias name ItemKey
     */
    public String getItemKey() {
        return (String) getAttributeInternal(ITEMKEY);
    }

    /**Sets <code>value</code> as attribute value for ITEM_KEY using the alias name ItemKey
     */
    public void setItemKey(String value) {
        setAttributeInternal(ITEMKEY, value);
    }

    /**Gets the attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE1 using the alias name Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String) getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE2 using the alias name Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String) getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE3 using the alias name Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String) getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE4 using the alias name Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String) getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as attribute value for ATTRIBUTE5 using the alias name Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number) getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_LOGIN using the alias name LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for the calculated attribute FundControllerDisp
     */
    public String getFundControllerDisp() {
        return (String) getAttributeInternal(FUNDCONTROLLERDISP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute FundControllerDisp
     */
    public void setFundControllerDisp(String value) {
        setAttributeInternal(FUNDCONTROLLERDISP, value);
    }

    /**Gets the attribute value for the calculated attribute ResponsibilityCenterDisp
     */
    public String getResponsibilityCenterDisp() {
        return (String) getAttributeInternal(RESPONSIBILITYCENTERDISP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute ResponsibilityCenterDisp
     */
    public void setResponsibilityCenterDisp(String value) {
        setAttributeInternal(RESPONSIBILITYCENTERDISP, value);
    }

    /**Gets the attribute value for the calculated attribute DisableAccountingMode
     */
    public Boolean getDisableAccountingMode() {
        return (Boolean) getAttributeInternal(DISABLEACCOUNTINGMODE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DisableAccountingMode
     */
    public void setDisableAccountingMode(Boolean value) {
        setAttributeInternal(DISABLEACCOUNTINGMODE, value);
    }

    /**Gets the attribute value for the calculated attribute DisableFundingAgency
     */
    public Boolean getDisableFundingAgency() {
        return (Boolean) getAttributeInternal(DISABLEFUNDINGAGENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute DisableFundingAgency
     */
    public void setDisableFundingAgency(Boolean value) {
        setAttributeInternal(DISABLEFUNDINGAGENCY, value);
    }

    /**Gets the attribute value for the calculated attribute SpCodeDisp
     */
    public String getSpCodeDisp() {
        return (String) getAttributeInternal(SPCODEDISP);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SpCodeDisp
     */
    public void setSpCodeDisp(String value) {
        setAttributeInternal(SPCODEDISP, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RIMFISCID:
            return getRimFiscId();
        case TRANSACTIONNO:
            return getTransactionNo();
        case CONSTITUENTUNIT:
            return getConstituentUnit();
        case RESPONSIBILITYCENTER:
            return getResponsibilityCenter();
        case COLLABORATINGAGENCY:
            return getCollaboratingAgency();
        case FUNDINGAGENCY:
            return getFundingAgency();
        case SPCODE:
            return getSpCode();
        case FUNDCONTROLLERID:
            return getFundControllerId();
        case FAREXCLUDED:
            return getFarExcluded();
        case ITEMKEY:
            return getItemKey();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case FUNDCONTROLLERDISP:
            return getFundControllerDisp();
        case SPCODEDISP:
            return getSpCodeDisp();
        case RESPONSIBILITYCENTERDISP:
            return getResponsibilityCenterDisp();
        case DISABLEACCOUNTINGMODE:
            return getDisableAccountingMode();
        case DISABLEFUNDINGAGENCY:
            return getDisableFundingAgency();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RIMFISCID:
            setRimFiscId((Number)value);
            return;
        case TRANSACTIONNO:
            setTransactionNo((Number)value);
            return;
        case CONSTITUENTUNIT:
            setConstituentUnit((String)value);
            return;
        case RESPONSIBILITYCENTER:
            setResponsibilityCenter((String)value);
            return;
        case COLLABORATINGAGENCY:
            setCollaboratingAgency((String)value);
            return;
        case FUNDINGAGENCY:
            setFundingAgency((String)value);
            return;
        case SPCODE:
            setSpCode((String)value);
            return;
        case FUNDCONTROLLERID:
            setFundControllerId((Number)value);
            return;
        case FAREXCLUDED:
            setFarExcluded((String)value);
            return;
        case ITEMKEY:
            setItemKey((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case FUNDCONTROLLERDISP:
            setFundControllerDisp((String)value);
            return;
        case SPCODEDISP:
            setSpCodeDisp((String)value);
            return;
        case RESPONSIBILITYCENTERDISP:
            setResponsibilityCenterDisp((String)value);
            return;
        case DISABLEACCOUNTINGMODE:
            setDisableAccountingMode((Boolean)value);
            return;
        case DISABLEFUNDINGAGENCY:
            setDisableFundingAgency((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


}
