package xxup.oracle.apps.per.rim.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMFundingRevVOImpl extends RIMVOParent {
    /**This is the default constructor (do not remove)
     */
    public RIMFundingRevVOImpl() {
    }

    /**Gets the bind variable value for pItemKey
     */
    public String getpItemKey() {
        return (String)getNamedWhereClauseParam("pItemKey");
    }

    /**Sets <code>value</code> for bind variable pItemKey
     */
    public void setpItemKey(String value) {
        setNamedWhereClauseParam("pItemKey", value);
    }
}
