package xxup.oracle.apps.per.rim.schema.server;

import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMFiscalDetailsEOImpl extends OAEntityImpl {
    public static final int RIMFISCID = 0;
    public static final int TRANSACTIONNO = 1;
    public static final int RESPONSIBILITYCENTER = 2;
    public static final int COLLABORATINGAGENCY = 3;
    public static final int FUNDINGAGENCY = 4;
    public static final int SPCODE = 5;
    public static final int FUNDCONTROLLERID = 6;
    public static final int FAREXCLUDED = 7;
    public static final int ITEMKEY = 8;
    public static final int ATTRIBUTE1 = 9;
    public static final int ATTRIBUTE2 = 10;
    public static final int ATTRIBUTE3 = 11;
    public static final int ATTRIBUTE4 = 12;
    public static final int ATTRIBUTE5 = 13;
    public static final int LASTUPDATEDATE = 14;
    public static final int LASTUPDATEDBY = 15;
    public static final int LASTUPDATELOGIN = 16;
    public static final int CREATEDBY = 17;
    public static final int CREATIONDATE = 18;
    public static final int CONSTITUENTUNIT = 19;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public RIMFiscalDetailsEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxup.oracle.apps.per.rim.schema.server.RIMFiscalDetailsEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for RimFiscId, using the alias name RimFiscId
     */
    public Number getRimFiscId() {
        return (Number)getAttributeInternal(RIMFISCID);
    }

    /**Sets <code>value</code> as the attribute value for RimFiscId
     */
    public void setRimFiscId(Number value) {
        setAttributeInternal(RIMFISCID, value);
    }

    /**Gets the attribute value for TransactionNo, using the alias name TransactionNo
     */
    public Number getTransactionNo() {
        return (Number)getAttributeInternal(TRANSACTIONNO);
    }

    /**Sets <code>value</code> as the attribute value for TransactionNo
     */
    public void setTransactionNo(Number value) {
        setAttributeInternal(TRANSACTIONNO, value);
    }


    /**Gets the attribute value for ResponsibilityCenter, using the alias name ResponsibilityCenter
     */
    public String getResponsibilityCenter() {
        return (String)getAttributeInternal(RESPONSIBILITYCENTER);
    }

    /**Sets <code>value</code> as the attribute value for ResponsibilityCenter
     */
    public void setResponsibilityCenter(String value) {
        setAttributeInternal(RESPONSIBILITYCENTER, value);
    }

    /**Gets the attribute value for CollaboratingAgency, using the alias name CollaboratingAgency
     */
    public String getCollaboratingAgency() {
        return (String)getAttributeInternal(COLLABORATINGAGENCY);
    }

    /**Sets <code>value</code> as the attribute value for CollaboratingAgency
     */
    public void setCollaboratingAgency(String value) {
        setAttributeInternal(COLLABORATINGAGENCY, value);
    }

    /**Gets the attribute value for FundingAgency, using the alias name FundingAgency
     */
    public String getFundingAgency() {
        return (String)getAttributeInternal(FUNDINGAGENCY);
    }

    /**Sets <code>value</code> as the attribute value for FundingAgency
     */
    public void setFundingAgency(String value) {
        setAttributeInternal(FUNDINGAGENCY, value);
    }

    /**Gets the attribute value for SpCode, using the alias name SpCode
     */
    public String getSpCode() {
        return (String)getAttributeInternal(SPCODE);
    }

    /**Sets <code>value</code> as the attribute value for SpCode
     */
    public void setSpCode(String value) {
        setAttributeInternal(SPCODE, value);
    }

    /**Gets the attribute value for FundControllerId, using the alias name FundControllerId
     */
    public Number getFundControllerId() {
        return (Number)getAttributeInternal(FUNDCONTROLLERID);
    }

    /**Sets <code>value</code> as the attribute value for FundControllerId
     */
    public void setFundControllerId(Number value) {
        setAttributeInternal(FUNDCONTROLLERID, value);
    }

    /**Gets the attribute value for FarExcluded, using the alias name FarExcluded
     */
    public String getFarExcluded() {
        return (String)getAttributeInternal(FAREXCLUDED);
    }

    /**Sets <code>value</code> as the attribute value for FarExcluded
     */
    public void setFarExcluded(String value) {
        setAttributeInternal(FAREXCLUDED, value);
    }

    /**Gets the attribute value for ItemKey, using the alias name ItemKey
     */
    public String getItemKey() {
        return (String)getAttributeInternal(ITEMKEY);
    }

    /**Sets <code>value</code> as the attribute value for ItemKey
     */
    public void setItemKey(String value) {
        setAttributeInternal(ITEMKEY, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RIMFISCID:
            return getRimFiscId();
        case TRANSACTIONNO:
            return getTransactionNo();
        case RESPONSIBILITYCENTER:
            return getResponsibilityCenter();
        case COLLABORATINGAGENCY:
            return getCollaboratingAgency();
        case FUNDINGAGENCY:
            return getFundingAgency();
        case SPCODE:
            return getSpCode();
        case FUNDCONTROLLERID:
            return getFundControllerId();
        case FAREXCLUDED:
            return getFarExcluded();
        case ITEMKEY:
            return getItemKey();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CONSTITUENTUNIT:
            return getConstituentUnit();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RIMFISCID:
            setRimFiscId((Number)value);
            return;
        case TRANSACTIONNO:
            setTransactionNo((Number)value);
            return;
        case RESPONSIBILITYCENTER:
            setResponsibilityCenter((String)value);
            return;
        case COLLABORATINGAGENCY:
            setCollaboratingAgency((String)value);
            return;
        case FUNDINGAGENCY:
            setFundingAgency((String)value);
            return;
        case SPCODE:
            setSpCode((String)value);
            return;
        case FUNDCONTROLLERID:
            setFundControllerId((Number)value);
            return;
        case FAREXCLUDED:
            setFarExcluded((String)value);
            return;
        case ITEMKEY:
            setItemKey((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CONSTITUENTUNIT:
            setConstituentUnit((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
        
        OADBTransaction tr = getOADBTransaction();
        if(getRimFiscId() == null){
            setRimFiscId(tr.getSequenceValue("XXUP.XXUP_RIM_FISCAL_SEQ"));
        }
    }

    /**Gets the attribute value for ConstituentUnit, using the alias name ConstituentUnit
     */
    public String getConstituentUnit() {
        return (String)getAttributeInternal(CONSTITUENTUNIT);
    }

    /**Sets <code>value</code> as the attribute value for ConstituentUnit
     */
    public void setConstituentUnit(String value) {
        setAttributeInternal(CONSTITUENTUNIT, value);
    }


    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number rimFiscId) {
        return new Key(new Object[]{rimFiscId});
    }
}
