package xxup.oracle.apps.per.rim.schema.server;

import oracle.apps.fnd.framework.server.OADBTransaction;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RIMPublicationEOImpl extends OAEntityImpl {
    public static final int RIMPUBLICATIONID = 0;
    public static final int TRANSACTIONNO = 1;
    public static final int ITEMKEY = 2;
    public static final int ISPUBLISHED = 3;
    public static final int DISTRIBUTIONMODE = 4;
    public static final int HASAWARD = 5;
    public static final int AWARDTITLE = 6;
    public static final int AWARDDATE = 7;
    public static final int CONFERRINGBODY = 8;
    public static final int POINTS = 9;
    public static final int POSTACTEVALRATING = 10;
    public static final int REMARKS = 11;
    public static final int ATTRIBUTE1 = 12;
    public static final int ATTRIBUTE2 = 13;
    public static final int ATTRIBUTE3 = 14;
    public static final int ATTRIBUTE4 = 15;
    public static final int ATTRIBUTE5 = 16;
    public static final int LASTUPDATEDATE = 17;
    public static final int LASTUPDATEDBY = 18;
    public static final int LASTUPDATELOGIN = 19;
    public static final int CREATEDBY = 20;
    public static final int CREATIONDATE = 21;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public RIMPublicationEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("xxup.oracle.apps.per.rim.schema.server.RIMPublicationEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);

        if (getRimPublicationId() == null) {
            OADBTransaction tr = getOADBTransaction();
            setRimPublicationId(tr.getSequenceValue("XXUP.XXUP_RIM_PUBLICATION_SEQ"));
        }
    }

    /**Gets the attribute value for RimPublicationId, using the alias name RimPublicationId
     */
    public Number getRimPublicationId() {
        return (Number)getAttributeInternal(RIMPUBLICATIONID);
    }

    /**Sets <code>value</code> as the attribute value for RimPublicationId
     */
    public void setRimPublicationId(Number value) {
        setAttributeInternal(RIMPUBLICATIONID, value);
    }

    /**Gets the attribute value for TransactionNo, using the alias name TransactionNo
     */
    public Number getTransactionNo() {
        return (Number)getAttributeInternal(TRANSACTIONNO);
    }

    /**Sets <code>value</code> as the attribute value for TransactionNo
     */
    public void setTransactionNo(Number value) {
        setAttributeInternal(TRANSACTIONNO, value);
    }

    /**Gets the attribute value for ItemKey, using the alias name ItemKey
     */
    public String getItemKey() {
        return (String)getAttributeInternal(ITEMKEY);
    }

    /**Sets <code>value</code> as the attribute value for ItemKey
     */
    public void setItemKey(String value) {
        setAttributeInternal(ITEMKEY, value);
    }

    /**Gets the attribute value for IsPublished, using the alias name IsPublished
     */
    public String getIsPublished() {
        return (String)getAttributeInternal(ISPUBLISHED);
    }

    /**Sets <code>value</code> as the attribute value for IsPublished
     */
    public void setIsPublished(String value) {
        setAttributeInternal(ISPUBLISHED, value);
    }

    /**Gets the attribute value for DistributionMode, using the alias name DistributionMode
     */
    public String getDistributionMode() {
        return (String)getAttributeInternal(DISTRIBUTIONMODE);
    }

    /**Sets <code>value</code> as the attribute value for DistributionMode
     */
    public void setDistributionMode(String value) {
        setAttributeInternal(DISTRIBUTIONMODE, value);
    }

    /**Gets the attribute value for HasAward, using the alias name HasAward
     */
    public String getHasAward() {
        return (String)getAttributeInternal(HASAWARD);
    }

    /**Sets <code>value</code> as the attribute value for HasAward
     */
    public void setHasAward(String value) {
        setAttributeInternal(HASAWARD, value);
    }

    /**Gets the attribute value for AwardTitle, using the alias name AwardTitle
     */
    public String getAwardTitle() {
        return (String)getAttributeInternal(AWARDTITLE);
    }

    /**Sets <code>value</code> as the attribute value for AwardTitle
     */
    public void setAwardTitle(String value) {
        setAttributeInternal(AWARDTITLE, value);
    }

    /**Gets the attribute value for AwardDate, using the alias name AwardDate
     */
    public Date getAwardDate() {
        return (Date)getAttributeInternal(AWARDDATE);
    }

    /**Sets <code>value</code> as the attribute value for AwardDate
     */
    public void setAwardDate(Date value) {
        setAttributeInternal(AWARDDATE, value);
    }

    /**Gets the attribute value for ConferringBody, using the alias name ConferringBody
     */
    public String getConferringBody() {
        return (String)getAttributeInternal(CONFERRINGBODY);
    }

    /**Sets <code>value</code> as the attribute value for ConferringBody
     */
    public void setConferringBody(String value) {
        setAttributeInternal(CONFERRINGBODY, value);
    }

    /**Gets the attribute value for Points, using the alias name Points
     */
    public Number getPoints() {
        return (Number)getAttributeInternal(POINTS);
    }

    /**Sets <code>value</code> as the attribute value for Points
     */
    public void setPoints(Number value) {
        setAttributeInternal(POINTS, value);
    }

    /**Gets the attribute value for PostActEvalRating, using the alias name PostActEvalRating
     */
    public String getPostActEvalRating() {
        return (String)getAttributeInternal(POSTACTEVALRATING);
    }

    /**Sets <code>value</code> as the attribute value for PostActEvalRating
     */
    public void setPostActEvalRating(String value) {
        setAttributeInternal(POSTACTEVALRATING, value);
    }

    /**Gets the attribute value for Remarks, using the alias name Remarks
     */
    public String getRemarks() {
        return (String)getAttributeInternal(REMARKS);
    }

    /**Sets <code>value</code> as the attribute value for Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**Gets the attribute value for Attribute1, using the alias name Attribute1
     */
    public String getAttribute1() {
        return (String)getAttributeInternal(ATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**Gets the attribute value for Attribute2, using the alias name Attribute2
     */
    public String getAttribute2() {
        return (String)getAttributeInternal(ATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for Attribute2
     */
    public void setAttribute2(String value) {
        setAttributeInternal(ATTRIBUTE2, value);
    }

    /**Gets the attribute value for Attribute3, using the alias name Attribute3
     */
    public String getAttribute3() {
        return (String)getAttributeInternal(ATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for Attribute3
     */
    public void setAttribute3(String value) {
        setAttributeInternal(ATTRIBUTE3, value);
    }

    /**Gets the attribute value for Attribute4, using the alias name Attribute4
     */
    public String getAttribute4() {
        return (String)getAttributeInternal(ATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for Attribute4
     */
    public void setAttribute4(String value) {
        setAttributeInternal(ATTRIBUTE4, value);
    }

    /**Gets the attribute value for Attribute5, using the alias name Attribute5
     */
    public String getAttribute5() {
        return (String)getAttributeInternal(ATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for Attribute5
     */
    public void setAttribute5(String value) {
        setAttributeInternal(ATTRIBUTE5, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RIMPUBLICATIONID:
            return getRimPublicationId();
        case TRANSACTIONNO:
            return getTransactionNo();
        case ITEMKEY:
            return getItemKey();
        case ISPUBLISHED:
            return getIsPublished();
        case DISTRIBUTIONMODE:
            return getDistributionMode();
        case HASAWARD:
            return getHasAward();
        case AWARDTITLE:
            return getAwardTitle();
        case AWARDDATE:
            return getAwardDate();
        case CONFERRINGBODY:
            return getConferringBody();
        case POINTS:
            return getPoints();
        case POSTACTEVALRATING:
            return getPostActEvalRating();
        case REMARKS:
            return getRemarks();
        case ATTRIBUTE1:
            return getAttribute1();
        case ATTRIBUTE2:
            return getAttribute2();
        case ATTRIBUTE3:
            return getAttribute3();
        case ATTRIBUTE4:
            return getAttribute4();
        case ATTRIBUTE5:
            return getAttribute5();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case CREATEDBY:
            return getCreatedBy();
        case CREATIONDATE:
            return getCreationDate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case RIMPUBLICATIONID:
            setRimPublicationId((Number)value);
            return;
        case TRANSACTIONNO:
            setTransactionNo((Number)value);
            return;
        case ITEMKEY:
            setItemKey((String)value);
            return;
        case ISPUBLISHED:
            setIsPublished((String)value);
            return;
        case DISTRIBUTIONMODE:
            setDistributionMode((String)value);
            return;
        case HASAWARD:
            setHasAward((String)value);
            return;
        case AWARDTITLE:
            setAwardTitle((String)value);
            return;
        case AWARDDATE:
            setAwardDate((Date)value);
            return;
        case CONFERRINGBODY:
            setConferringBody((String)value);
            return;
        case POINTS:
            setPoints((Number)value);
            return;
        case POSTACTEVALRATING:
            setPostActEvalRating((String)value);
            return;
        case REMARKS:
            setRemarks((String)value);
            return;
        case ATTRIBUTE1:
            setAttribute1((String)value);
            return;
        case ATTRIBUTE2:
            setAttribute2((String)value);
            return;
        case ATTRIBUTE3:
            setAttribute3((String)value);
            return;
        case ATTRIBUTE4:
            setAttribute4((String)value);
            return;
        case ATTRIBUTE5:
            setAttribute5((String)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number rimPublicationId) {
        return new Key(new Object[]{rimPublicationId});
    }
}
